ros-visualization/rqt_common_plugins

rqt_top/src/rqt_top/node_info.py

In connection to [rqt_top: Restarted nodes do not reappear #294](https://github.com/ros-visualization/rqt_common_plugins/issues/294) I created a pull request to fix the problem of restarted nodes not reappearing in the list of rqt_top.

Fixed issue with rqt_top: Restarted nodes do not reappear

---

rqt_bag/resource/bag_widget.ui
rqt_bag/src/rqt_bag/bag_timeline.py
rqt_bag/src/rqt_bag/bag_widget.py

rqt_bag : Addition of buttons to allow a message-by-message navigation in the bag

rqt_bag : Addition of a step-by-step play

---

rqt_reconfigure/resource/node_selector.ui
rqt_reconfigure/src/rqt_reconfigure/node_selector_widget.py
rqt_reconfigure/src/rqt_reconfigure/treenode_qstditem.py

Includes fix from https://github.com/ros-visualization/rqt_common_plugins/pull/297 with additional work to make the _refresh_nodes method work more cleanly.
Thanks,
--scott

rqt_reconfigure: add refresh button

---

rqt_image_view/include/rqt_image_view/image_view.h
rqt_image_view/include/rqt_image_view/ratio_layouted_frame.h
rqt_image_view/src/rqt_image_view/image_view.cpp
rqt_image_view/src/rqt_image_view/image_view.ui
rqt_image_view/src/rqt_image_view/ratio_layouted_frame.cpp

@ablasdel Can you please give this a try?
I used `rosrun usb_cam usb_cam_node` to feed it with images.

[rqt_image_view] add button to save current image to file

---

rqt_topic/src/rqt_topic/topic.py
rqt_topic/src/rqt_topic/topic_widget.py

Current value is clearly the most important of these fields and should come first by default.

rqt_topic: Save/Restore header state, Column ordering

---

rqt_plot/src/rqt_plot/plot_widget.py
rqt_publisher/src/rqt_publisher/publisher_tree_widget.py
rqt_publisher/src/rqt_publisher/publisher_widget.py

as detailed in http://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html

use proper icon names for add/remove

---

rqt_image_view/src/rqt_image_view/image_view.cpp

as detailed here http://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html

use proper icon for images

---

rqt_graph/src/rqt_graph/dotcode.py

Prefix all node and topic names with `n:` and `t:` respectively, to allow dot to distinguish them

Fixes #333

---

rqt_topic/src/rqt_topic/topic_info.py

check for divide by zero and data failures

---

rqt_bag/src/rqt_bag/bag_timeline.py

Related to #320 ; not really a neat fix but it works.

Pass y from scene to map_y_to_topic function

---

rqt_plot/package.xml

rqt_plot: add missing dependency on numpy

---

rqt_dep/test/dotcode_pack_test.py

Fixes failing test with newer mock version: http://build.ros.org/job/Kdev__rqt_common_plugins__ubuntu_xenial_amd64/

fix newer mock version

---

rqt_console/src/rqt_console/console_widget.py

rqt_console: make message column stretch

---

rqt_bag_plugins/src/rqt_bag_plugins/plot_view.py

Should resolve race conditions when multiple threads are trying to resample the bag at the same time.
Fixes http://answers.ros.org/question/234669/why-does-rqt_bag-often-fail-to-plot-data/

Lock bag when reading for plotting

---

rqt_image_view/CMakeLists.txt

Fix CMake warning: http://build.ros.org/job/Kdev__rqt_common_plugins__ubuntu_xenial_amd64/15/warnings2Result/

generated ui headers in devel space to avoid catkin CMake warning

---

rqt_bag/src/rqt_bag/bag_timeline.py

b.size actually seeks in the bag resulting in a race condition with the
bag reader.

Lock bag before reading it's size

---

rqt_launch/resource/launch_widget.ui
rqt_launch/src/rqt_launch/launch_main.py
rqt_launch/src/rqt_launch/launch_widget.py

Let me know if you have any suggestions for improvement. Thanks.

Fixes #341: Adding feature to load all params in a launch config onto parameter server

---

rqt_reconfigure/src/rqt_reconfigure/dynreconf_client_widget.py

Adds basic functionality to save and load dynamic parameter configurations per node via the rqt_reconfigure GUI.
It's worth noting that saving and loading dynamic parameters is broken on Kinetic right now with debians and requires ros/dynamic_reconfigure#61 (which has been merged to master but was not released).

Add 'save' and 'load' buttons to rqt_reconfigure

---

rqt_console/src/rqt_console/message_proxy_model.py

fix regression with Qt 4

---

rqt_plot/src/rqt_plot/data_plot/pyqtgraph_data_plot.py

reenable PyQtGraph when version >= 0.10

---

rqt_topic/src/rqt_topic/topic_widget.py

This crash can be triggered by killing the rosmaster while rqt is running with an activated topic_widget.
I used _roslaunch turtle_tf2 turtle_tf2_demo.launch_ in one terminal while having _rqt_ in a second one.
When stopping the nodes and master in terminal one by Ctrl+C this Traceback occured due to the lost connection:
```
Traceback (most recent call last):
File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_topic/topic_widget.py", line 123, in refresh_topics
topic_list = rospy.get_published_topics()
File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/client.py", line 379, in get_published_topics
code, msg, val = get_master().getPublishedTopics(namespace)
File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/msproxy.py", line 106, in wrappedF
return f(*args, **kwds)
File …
```

Catching unhandled IOError exceptions if connection to rosmaster gets lost

---

rqt_launch/src/rqt_launch/node_controller.py

remove __slots__ declaration

---

rqt_shell/scripts/rqt_shell
rqt_shell/setup.py
rqt_shell/src/rqt_shell/shell.py
rqt_shell/src/rqt_shell/shell_text_edit.py
rqt_shell/src/rqt_shell/shell_widget.py
rqt_shell/src/rqt_shell/spyder_shell_widget.py
rqt_shell/src/rqt_shell/xterm_widget.py

Got lost somewhere. But back again. 
@ablasdel I'm afraid I forgot how to test this.

Start shell with a load script (Issue #296)

---

rqt_topic/src/rqt_topic/topic_info.py

fix buffer length

---

rqt_top/src/rqt_top/node_info.py

proposed solution for issue #443. small import error

---

rqt_web/package.xml

add missing webkit dependency

---

rqt_dep/resource/RosPackGraph.ui
rqt_dep/src/rqt_dep/dotcode_pack.py
rqt_dep/src/rqt_dep/ros_pack_graph.py

Code modeled after hide_transitives

Add option to show system dependencies using rospack.get_rosdeps

---

package.xml

This conversion will make the diff minimal with a potential ROS2 version of that metapackage
Signed-off-by: Mikael Arguedas <mikael.arguedas@gmail.com>

convert to package format 2

---

package.xml

I only updated the default branch before, but updating the `ros2` branch for clarity.

[ros2] Update maintainers
