ros-visualization/rqt_common_plugins

- rqt_plot/src/rqt_plot/data_plot/mat_data_plot.py
When PyQt5 is installed, matplotlib uses the Qt5 backend by default, so we need to force the usage of the Qt4 backend.
> Fix version clash when PyQt5 is installed

- rqt_reconfigure/src/rqt_reconfigure/paramedit_widget.py
Instead of specifically specifying the background color to make the colors alternate, modify the theme's set background color to be "lighter" and "darker".
Values chosen to most closely resemble the current behavior with a light theme.
Suggested fix for https://github.com/ros-visualization/rqt_common_plugins/pull/293
Tested on Ubuntu Trusty and Fedora 21 with light and dark themes.
Screenshot with Adwaita dark style theme:
**EDIT**: Screenshot with Adwaita dark style theme before fix:
**EDIT**: Screenshot with Adwaita light theme after fix (no significant difference) :
> rqt_reconfigure: Fix background colors for dark themes

- rqt_plot/src/rqt_plot/data_plot/__init__.py
New users are confused by the log messages indicating that some of the rqt_plot backends are not found. These debug messages should be removed from the console log, and a message indicating that the backends aren't installed should be added to the backend selection dialog.
I've seen this 3 or 4 times in as many months on ROS answers; the most recent occurrence is: http://answers.ros.org/question/201721/rxplot-not-found/?answer=201784#post-id-201784
> rqt_plot: remove warning/debug message when backend not found

- rqt_bag/src/rqt_bag/bag_timeline.py
- rqt_bag/src/rqt_bag/player.py
- rqt_bag/src/rqt_bag/timeline_frame.py
Due to parallelism issues, a message can be published with a simulated timestamp in the past. This lead to undesired behaviors when using TF for example.
In this PR, when --clock is passed, if the timestamp of the new message to be published is older than the last published clock message, the new clock is dropped but the message is published.
> RQT_BAG: Ensure monotonic clock publishing.

- rqt_top/src/rqt_top/node_info.py
The code contains:
```python
try:
...
except AccessDenied:
ret = ad_value
```
`AccessDenied` is a psutil exception, thus I obtained the following error:
```txt
File "/opt/ros/indigo/lib/python2.7/site-packages/rqt_top/node_info.py", line 69, in get_all_node_fields
infos.append(self.as_dict(p, fields + ['cmdline', 'get_memory_info']))
File "/opt/ros/indigo/lib/python2.7/site-packages/rqt_top/node_info.py", line 105, in as_dict
except AccessDenied:
NameError: global name 'AccessDenied' is not defined
```
This PR fixes that. I also found incompatibilities with psutil's new API (see #349), but I doubt the error described here is related to that.
> rqt_top: fix exception handling

- rqt_graph/resource/RosGraph.ui
This makes the graph window able to become a little narrower, which really makes a difference when on small screens, or with lots of panes.
Before:
After:
> Remove repeated prefices from buttons

- rqt_plot/src/rqt_plot/data_plot/mat_data_plot.py
Replaces #343.
It uses a more defensive approach in case users are using an older version which doesn't have the new import.
> check alternative matplotplot 1.5 module name

- rqt_image_view/CMakeLists.txt
- rqt_image_view/include/rqt_image_view/image_view.h
- rqt_image_view/include/rqt_image_view/ratio_layouted_frame.h
- rqt_image_view/package.xml
- rqt_image_view/src/rqt_image_view/image_view.cpp
- rqt_image_view/src/rqt_image_view/image_view.ui
- rqt_image_view/src/rqt_image_view/ratio_layouted_frame.cpp
@ablasdel Merging #331 into master as requested. Apologies about the delay.
> rqt_image_view: Adding the possibility to publish mouse events.

- rqt_reconfigure/src/rqt_reconfigure/paramedit_widget.py
Fixes this issue:
https://github.com/ros-visualization/rqt_common_plugins/issues/369
> rqt_reconfigure: fix accessing attribute superseded in Qt5

- rqt_bag_plugins/src/rqt_bag_plugins/image_timeline_renderer.py
Fixes the crash in image_timeline_renderer.py when toggling thumbnails in rqt_bag.
Seems like the constructor for QPen expects a QColor and not a QBrush.
> Issue#380 fix crash when toggling thumbnail in rqt_bag

- rqt_plot/src/rqt_plot/data_plot/pyqtgraph_data_plot.py
Fixes ros-visualization/rqt#109.
> disable PyQtGraph backend when Qt 5 is being used

- rqt_msg/src/rqt_msg/messages_widget.py
While using the plugin I noticed that you can only add message but not remove them. This patch adds a remove action to the context menu to resolve that.
> add remove action to context menu in message type browser

- rqt_console/package.xml
> [rqt_console] add missing dependency on rqt_py_common

- rqt_image_view/include/rqt_image_view/ratio_layouted_frame.h
- rqt_image_view/src/rqt_image_view/image_view.cpp
- rqt_image_view/src/rqt_image_view/image_view.ui
- rqt_image_view/src/rqt_image_view/ratio_layouted_frame.cpp
Is there a reason for not using the `Qt::SmoothTransformation` when scaling the image inside the `ratio_layouted_frame`? If not I would propose this change. Especially low resolution images e.g. from thermal cameras look much better when scaled.
> rqt_image_view: use smooth transformation for image scaling

- rqt_bag_plugins/src/rqt_bag_plugins/image_timeline_renderer.py
- rqt_bag_plugins/src/rqt_bag_plugins/image_view.py
Similar to https://github.com/ros-visualization/rqt_common_plugins/issues/424, without this PR I get the following error when I click `Toggle Thumbnail` button after loading a `.bag` file that contains image topics.
```
$ rqt&
$ Loading /home/rosnoodle/Desktop/2017-01-30-15-03-19.bag
Done loading /home/rosnoodele/Desktop/2017-01-30-15-03-19.bag
Error loading image on topic /camera/image_raw: global name 'image_helper' is not defined
Disabling renderer on /camera/image_raw
$ rospack find rqt_bag
/home/rosnoodele/cws_viz/src/ros-visualization/rqt_common_plugins/rqt_bag
$ roscd rqt_bag
$ git log
commit 2c2487a02c83628a14be7bde318d20249167ffdb
Author: Dirk Thomas <dthomas@osrfoundation.org>
Date:   Tue Jan 31 12:35:55 2017 -0800
fix bag_helper import
:
```
(For testing I used [this bag …
> [fix][rqt_bag_plugins] 'image_helper' is not defined" error.

- rqt_plot/src/rqt_plot/plot_widget.py
Add the capability to plot bool fields in composite messages.
> rqt_plot: Plot bool fields

- rqt_graph/src/rqt_graph/dotcode.py
self.edges[sub][topic].keys() returns a list, while next() expects an iterator, which leads to a TypeError: list object is not an iterator exception. Fixed by converting key list to iterator first (this solution works both in Python 2 and 3).
> Fix crash of rqt_graph when enable_statistics == true, fixes #428

- rqt_image_view/src/rqt_image_view/image_view.cpp
This is for #430 .  Now passing in a topic from the command line or restoring a saved setting behave identically, if the topic doesn't yet exist it is added to the list of available topics.  Also, hitting refresh will keep the current topic subscribed and available from the dropdown menu even if it isn't publishing.
> [rqt_image_view] subscribe to saved topic even if it is not available yet

- rqt_graph/resource/RosGraph.ui
- rqt_graph/src/rqt_graph/dotcode.py
- rqt_graph/src/rqt_graph/ros_graph.py
The description of debug is given as `Hide common debugging nodes`. Without this patch it also hides nodes that rqt_graph cannot connect to as they are marked as Bad Nodes.
This creates a problem when rqt_graph can only connect to the ROS master as all nodes are marked as bad nodes. Debug can be shown but then the graph is polluted with `/rosout` connections and the nodes are drawn as large red circles.
To fix this I have stopped quiet (debug) affecting bad nodes being shown and I have also  changed the nodes so they are shown as colored ellipses similar to working nodes.
> [rqt_graph] Show bad nodes even if debug (quiet) is set

- rqt_image_view/src/rqt_image_view/image_view.cpp
- rqt_image_view/src/rqt_image_view/image_view.ui
When selecting a 1-to-1 pixel view, the previous implementation resized the
window to the full image size. This is inconvenient for images much larger than
the screen resolution. This patch places the RatioLayoutedFrame in a ScrollArea
so the window still fits on the screen and the user can pan on the full image.
> [rqt_image_view] Add a scroll area

- package.xml
rqt_bag is now available for ROS2 in the Rolling release. 
Signed-off-by: Michael Jeronimo <michael.jeronimo@openrobotics.org>
> Add rqt_bag to the rqt_common_plugins metapackage

- package.xml
These are ones that either don't work well, or have never
been ported to ROS 2.  We can always add them back if we
port them over.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
> Remove unreleased plugins from rqt_common_plugins.
